name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]

assignees:
  - tryin2bdeveloper
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "The workflow fails to execute due to unit tests not passing. Specifically, the tests for the authentication module return unexpected results, preventing the build from completing."
    validations:
      required: true
  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: Describe what you expected to happen.
      placeholder: What should have happened?
      value: "The unit tests should run successfully, allowing the workflow to proceed without errors and enabling a smooth deployment process."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - latest (Default)
        - 0.1-alpha-2 (Edge)
        - 0.1-alpha-4 (Edge)
        - 0.1-alpha-6 (Edge)
    validations:
      required: true