name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]

assignees:
  - tryin2bdeveloper
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: What did you expect to happen?
      options:
        - ""  # This creates a blank option
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - latest (Default)
        - 0.1-alpha-2 (Edge)
        - 0.1-alpha-4 (Edge)
        - 0.1-alpha-6 (Edge)
    validations:
      required: true