name: Feature Request
description: Propose a new feature for the project.
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - tryin2bdeveloper
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature!
  - type: textarea
    id: feature-details
    attributes:
      label: Feature Description
      description: What feature would you like to see implemented?
      placeholder: Describe your feature idea here
    validations:
      required: true
  - type: input
    id: priority
    attributes:
      label: Priority Level
      description: Is this feature high or low priority?
      placeholder: High/Low
    validations:
      required: true