name: Security Vulnerability
description: Report a potential security issue.
title: "[Security]: "
labels: ["security"]
assignees:
  - tryin2bdeveloper
body:
  - type: markdown
    attributes:
      value: |
        Please disclose any security issues privately before reporting publicly.
  - type: input
    id: vulnerability-details
    attributes:
      label: Vulnerability Details
      description: Describe the security issue you found.
      placeholder: Outline the issue here
    validations:
      required: true
  - type: input
    id: severity
    attributes:
      label: Severity
      description: How severe is the vulnerability?
      placeholder: Critical/High/Medium/Low
    validations:
      required: true