name: CodeReview - 3

on:
  push:
    branches:
      - master
      - develop

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Database Docker Image
        run: docker build -t database ./db

      - name: Start Database Container for Unit Tests
        run: docker run --name unit-database -d -p 33060:3306 database

      - name: Wait for Database to Initialize
        run: |
          echo "Waiting for database to start..."
          for i in {1..10}; do
            if docker exec unit-database mysqladmin ping -h "localhost" --silent; then
              echo "Database is up!"
              break
            fi
            echo "Waiting for the database..."
            sleep 5
          done
      - name: Run Unit Tests
        run: mvn -Dtest=com.napier.devops.AppTest test

      - name: Stop and Clean up Docker (Unit Tests)
        run: |
          docker stop unit-database
          docker rm unit-database
          docker image rm database
  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Database Docker Image
        run: docker build -t database ./db

      - name: Start Database Container for Integration Tests
        run: docker run --name integration-database -d -p 33060:3306 database

      - name: Wait for Database to Initialize
        run: |
          echo "Waiting for database to start..."
          for i in {1..10}; do
            if docker exec integration-database mysqladmin ping -h "localhost" --silent; then
              echo "Database is up!"
              break
            fi
            echo "Waiting for the database..."
            sleep 5
          done
      - name: Run Integration Tests
        run: mvn -Dtest=com.napier.devops.AppIntegrationTest test

      - name: Stop and Clean up Docker (Integration Tests)
        run: |
          docker stop integration-database
          docker rm integration-database
          docker image rm database

      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./target/site/jacoco
          flags: Integration Tests # optional
          verbose: true # optional (default = false)


  build:
    name: Build and Start Using docker compose
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit
