name: Code Review 3
on:
  push:
    branches:
      - master
      - develop
jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run Unit Tests
        run: mvn -Dtest=com.napier.devops.AppTest test

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and Start Database
        run: |
          docker build -t database ./db 
          docker run --name employees -d -p 33060:3306 database
          # Wait for the database to initialize
          echo "Waiting for the database to start..."
          for i in {1..10}; do
            if docker exec employees mysqladmin ping -h "localhost" --silent; then
              echo "Database is up!"
              break
            fi
            echo "Waiting for the database..."
            sleep 5
          done
      - name: Run Integration Tests
        run: mvn -Dtest=com.napier.devops.AppIntegrationTest test
      - name: Stop and Remove Docker Container
        run: |
          docker stop employees
          docker rm employees
          docker image rm database
      - name: Verify Coverage Report
        run: |
          if [ ! -f ./target/site/jacoco/jacoco.xml ]; then
            echo "Coverage report not found!"
            exit 1
          fi
      - name: Upload Code Coverage to CodeCov
        uses: codecov/codecov-action@v2
        with:
          directory: ./target/site/jacoco
          flags: Integration Tests
          verbose: true

  build:
    name: Build and Start Using docker compose
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit