name: Workflow for Deploy Latest Release

on:
  push:
    branches:
      - master
      - develop
      - release

# Define permissions at the workflow level
permissions:
  contents: write  # Allows writing to the repository, needed for releases
  issues: read     # Optional, adjust as needed
  pull-requests: read  # Optional, adjust as needed
  actions: read    # Optional, adjust as needed

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Build and run the database as in the first workflow
      - name: Build Database Docker Image
        run: docker build -t database ./db

      - name: Start Database Container for Unit Tests
        run: docker run --name unit-database -d -p 33060:3306 database

      - name: Wait for Database to Initialize
        run: |
          echo "Waiting for database to start..."
          for i in {1..10}; do
            if docker exec unit-database mysqladmin ping -h "localhost" --silent; then
              echo "Database is up!"
              break
            fi
            echo "Waiting for the database..."
            sleep 5
          done

      - name: Run Unit Tests
        run: mvn -Dtest=com.napier.devops.AppTest test

      - name: CodeCov
        uses: codecov/codecov-action@v4
        with:
          directory: ./target/site/jacoco
          flags: Unit Tests # optional
          verbose: true     # optional (default = false)

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Integration Tests and CodeCov
        run: |
          docker build -t database ./db 
          docker run --name employees -dp 33060:3306 database
          mvn -Dtest=com.napier.devops.AppIntegrationTest test          
          docker stop employees
          docker rm employees
          docker image rm database

      - name: CodeCov
        uses: codecov/codecov-action@v4
        with:
          directory: ./target/site/jacoco
          flags: Integration Tests # optional
          verbose: true            # optional (default = false)

  BuildAndRelease:
    name: Build Run in Docker and Deploy Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Package and Run Docker Compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit

      - name: Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/*.jar