name: Workflow for Population Report Java Application
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Population Report
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test with Maven
        run: mvn clean test -Dtest=com.napier.devops.AppTest

      - name: Package with Maven (Skipping Tests)
        run: mvn package -DskipTests

      - name: Run Docker Compose
        run: docker compose up --abort-on-container-exit
